export const ADMIN_PRODUCT_DETAILS_REQUEST = 'ADMIN_PRODUCT_DETAILS_REQUEST';
export const ADMIN_PRODUCT_DETAILS_SUCCESS = 'ADMIN_PRODUCT_DETAILS_SUCCESS';
export const ADMIN_PRODUCT_DETAILS_FAIL = 'ADMIN_PRODUCT_DETAILS_FAIL';
