export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_LOAD_MORE_REQUEST = 'PRODUCT_LOAD_MORE_REQUEST';
export const PRODUCT_LOAD_MORE_SUCCESS = 'PRODUCT_LOAD_MORE_SUCCESS';
export const PRODUCT_LOAD_MORE_FAIL = 'PRODUCT_LOAD_MORE_FAIL';
