export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST';
export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS';
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL';

export const ADMIN_USER_ACTIVATE = 'ADMIN_USER_ACTIVATE';
export const ADMIN_USER_DEACTIVATE = 'ADMIN_USER_DEACTIVATE';

export const ADMIN_USER_MAKE_ADMIN = 'ADMIN_USER_MAKE_ADMIN';
export const ADMIN_USER_MAKE_SUBSCRIBER = 'ADMIN_USER_MAKE_SUBSCRIBER';
