export const SHOW_SEARCHBAR = 'SHOW_SEARCHBAR';
export const HIDE_SEARCHBAR = 'HIDE_SEARCHBAR';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const CLEAR_SEARCH_QUERY = 'CLEAR_SEARCH_QUERY';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
