export const ADMIN_PRODUCT_LIST_REQUEST = 'ADMIN_PRODUCT_LIST_REQUEST';
export const ADMIN_PRODUCT_LIST_SUCCESS = 'ADMIN_PRODUCT_LIST_SUCCESS';
export const ADMIN_PRODUCT_LIST_FAIL = 'ADMIN_PRODUCT_LIST_FAIL';
