export const ADMIN_ORDER_LIST_REQUEST = 'ADMIN_ORDER_LIST_REQUEST';
export const ADMIN_ORDER_LIST_SUCCESS = 'ADMIN_ORDER_LIST_SUCCESS';
export const ADMIN_ORDER_LIST_FAIL = 'ADMIN_ORDER_LIST_FAIL';

export const ADMIN_ORDER_DELETE = 'ADMIN_ORDER_DELETE';
