export const ADMIN_ORDER_DETAILS_REQUEST = 'ADMIN_ORDER_DETAILS_REQUEST';
export const ADMIN_ORDER_DETAILS_SUCCESS = 'ADMIN_ORDER_DETAILS_SUCCESS';
export const ADMIN_ORDER_DETAILS_FAIL = 'ADMIN_ORDER_DETAILS_FAIL';

export const ADMIN_ORDER_DELIVER_REQUEST = 'ADMIN_ORDER_DELIVER_REQUEST';
export const ADMIN_ORDER_DELIVER_SUCCESS = 'ADMIN_ORDER_DELIVER_SUCCESS';
export const ADMIN_ORDER_DELIVER_FAIL = 'ADMIN_ORDER_DELIVER_FAIL';
