export const ADMIN_ORDER_DETAILS_REQUEST = 'ADMIN_ORDER_DETAILS_REQUEST';
export const ADMIN_ORDER_DETAILS_SUCCESS = 'ADMIN_ORDER_DETAILS_SUCCESS';
export const ADMIN_ORDER_DETAILS_FAIL = 'ADMIN_ORDER_DETAILS_FAIL';
