export const ADMIN_PRODUCT_CREATE_REQUEST = 'ADMIN_PRODUCT_CREATE_REQUEST';
export const ADMIN_PRODUCT_CREATE_SUCCESS = 'ADMIN_PRODUCT_CREATE_SUCCESS';
export const ADMIN_PRODUCT_CREATE_FAIL = 'ADMIN_PRODUCT_CREATE_FAIL';

export const ADMIN_PRODUCT_RESET = 'ADMIN_PRODUCT_RESET';

export const ADMIN_PRODUCT_UPLOAD_REQUEST = 'ADMIN_PRODUCT_UPLOAD_REQUEST';
export const ADMIN_PRODUCT_UPLOAD_SUCCESS = 'ADMIN_PRODUCT_UPLOAD_SUCCESS';
export const ADMIN_PRODUCT_UPLOAD_FAIL = 'ADMIN_PRODUCT_UPLOAD_FAIL';
